### ISSUE TITLE
Basic example explodes with error

### ISSUE THREAD

**Issue by kirillsalykin** [maxcountryman/underway#22]
I've followed basic example and tried to adapt it my project. https://github.com/maxcountryman/underway/blob/main/examples/basic/src/main.rs)

Unfortunately I see panic on `job.run().await.unwrap()`:

```
thread 'main' panicked at /src/lib.rs:106:25:
called `Result::unwrap()` on an `Err` value: Scheduler(Queue(Database(RowNotFound)))
```

but `job.run_worker().await.unwrap();` works just fine.
So I think job.run assumes that there is always scheduler row, but obviously it is not.

**Comment by maxcountryman** [comment]
Fixed in the step functions branch.
