### ISSUE TITLE
Add example to run underway next to `axum`

### ISSUE THREAD

**Issue by kirillsalykin** [maxcountryman/underway#23]
Could you please add example which shows how to run both `underway` and `axum`?
(maybe some API changes would be needed)?

Both axum and underway use tokio and do block the thread, so I assume `select!` would be required, the problem is that `underway` doesnt expose job/worker part I can select on.

Should I wrap `job.run` in tokio::spawn and select on it?

Thanks!

P.S. This probably will may change the way graceful shutdown implemented now, it feels more natural (to me at least) run stop the job, not the queue

**Comment by maxcountryman** [comment]
You spawn run, correct. In the step functions branch you can use start to do this transparently.
